/// Create a list of Cityname;Temperature meassurements 
/// TK11NOV2024-24Nov2024
/// Converted from create-sample.c from https://github.com/dannyvankooten/1brc/blob/main/create-sample.c
/// For larger numbers of samples run in release mode!
/// usage: cargo run --bin create-sample --release 10000000000 measurements.txt
///        cargo run --bin create-sample --release 10000000000 | gzip >measurents.txt.gz
/// The programm will print a "." to stderr every 10 mill lines.

use std::env;
use rand::SeedableRng;
use rand::rngs::StdRng;
use rand_distr::{Normal, Uniform, Distribution};
use std::fs::File;
use std::io::{Write, BufWriter, stdout, stderr};

struct CityData {
    name: &'static str,  // Using &'static str for string literals
    mean: f64,
}

/// = Example = 
/// create-samples 10000 >measurements10k.csv
///
fn main() {
    let cities = [
		CityData { name: "Abha", mean: 18.0 },
        CityData { name: "Abidjan", mean: 26.0 },
        CityData { name: "Abéché", mean: 29.4 },
        CityData { name: "Accra", mean: 26.4 },
        CityData { name: "Addis Ababa", mean: 16.0 },
        CityData { name: "Adelaide", mean: 17.3 },
        CityData { name: "Aden", mean: 29.1 },
        CityData { name: "Ahvaz", mean: 25.4 },
        CityData { name: "Albuquerque", mean: 14.0 },
        CityData { name: "Alexandra", mean: 11.0 },
        CityData { name: "Alexandria", mean: 20.0 },
        CityData { name: "Algiers", mean: 18.2 },
        CityData { name: "Alice Springs", mean: 21.0 },
        CityData { name: "Almaty", mean: 10.0 },
        CityData { name: "Amsterdam", mean: 10.2 },
        CityData { name: "Anadyr", mean: -6.9 },
        CityData { name: "Anchorage", mean: 2.8 },
        CityData { name: "Andorra la Vella", mean: 9.8 },
        CityData { name: "Ankara", mean: 12.0 },
        CityData { name: "Antananarivo", mean: 17.9 },
        CityData { name: "Antsiranana", mean: 25.2 },
        CityData { name: "Arkhangelsk", mean: 1.3 },
        CityData { name: "Ashgabat", mean: 17.1 },
        CityData { name: "Asmara", mean: 15.6 },
        CityData { name: "Assab", mean: 30.5 },
        CityData { name: "Astana", mean: 3.5 },
        CityData { name: "Athens", mean: 19.2 },
        CityData { name: "Atlanta", mean: 17.0 },
        CityData { name: "Auckland", mean: 15.2 },
        CityData { name: "Austin", mean: 20.7 },
        CityData { name: "Baghdad", mean: 22.77 },
        CityData { name: "Baguio", mean: 19.5 },
        CityData { name: "Baku", mean: 15.1 },
        CityData { name: "Baltimore", mean: 13.1 },
        CityData { name: "Bamako", mean: 27.8 },
        CityData { name: "Bangkok", mean: 28.6 },
        CityData { name: "Bangui", mean: 26.0 },
        CityData { name: "Banjul", mean: 26.0 },
        CityData { name: "Barcelona", mean: 18.2 },
        CityData { name: "Bata", mean: 25.1 },
        CityData { name: "Batumi", mean: 14.0 },
        CityData { name: "Beijing", mean: 12.9 },
        CityData { name: "Beirut", mean: 20.9 },
        CityData { name: "Belgrade", mean: 12.5 },
        CityData { name: "Belize City", mean: 26.7 },
        CityData { name: "Benghazi", mean: 19.9 },
        CityData { name: "Bergen", mean: 7.7 },
        CityData { name: "Berlin", mean: 10.3 },
        CityData { name: "Bilbao", mean: 14.7 },
        CityData { name: "Birao", mean: 26.5 },
        CityData { name: "Bishkek", mean: 11.3 },
        CityData { name: "Bissau", mean: 27.0 },
        CityData { name: "Blantyre", mean: 22.2 },
        CityData { name: "Bloemfontein", mean: 15.6 },
        CityData { name: "Boise", mean: 11.4 },
        CityData { name: "Bordeaux", mean: 14.2 },
        CityData { name: "Bosaso", mean: 30.0 },
        CityData { name: "Boston", mean: 10.9 },
        CityData { name: "Bouaké", mean: 26.0 },
        CityData { name: "Bratislava", mean: 10.5 },
        CityData { name: "Brazzaville", mean: 25.0 },
        CityData { name: "Bridgetown", mean: 27.0 },
        CityData { name: "Brisbane", mean: 21.4 },
        CityData { name: "Brussels", mean: 10.5 },
        CityData { name: "Bucharest", mean: 10.8 },
        CityData { name: "Budapest", mean: 11.3 },
        CityData { name: "Bujumbura", mean: 23.8 },
        CityData { name: "Bulawayo", mean: 18.9 },
        CityData { name: "Burnie", mean: 13.1 },
        CityData { name: "Busan", mean: 15.0 },
        CityData { name: "Cabo San Lucas", mean: 23.9 },
        CityData { name: "Cairns", mean: 25.0 },
        CityData { name: "Cairo", mean: 21.4 },
        CityData { name: "Calgary", mean: 4.4 },
        CityData { name: "Canberra", mean: 13.1 },
        CityData { name: "Cape Town", mean: 16.2 },
        CityData { name: "Changsha", mean: 17.4 },
        CityData { name: "Charlotte", mean: 16.1 },
        CityData { name: "Chiang Mai", mean: 25.8 },
        CityData { name: "Chicago", mean: 9.8 },
        CityData { name: "Chihuahua", mean: 18.6 },
        CityData { name: "Chișinău", mean: 10.2 },
        CityData { name: "Chittagong", mean: 25.9 },
        CityData { name: "Chongqing", mean: 18.6 },
        CityData { name: "Christchurch", mean: 12.2 },
        CityData { name: "City of San Marino", mean: 11.8 },
        CityData { name: "Colombo", mean: 27.4 },
        CityData { name: "Columbus", mean: 11.7 },
        CityData { name: "Conakry", mean: 26.4 },
        CityData { name: "Copenhagen", mean: 9.1 },
        CityData { name: "Cotonou", mean: 27.2 },
        CityData { name: "Cracow", mean: 9.3 },
        CityData { name: "Da Lat", mean: 17.9 },
        CityData { name: "Da Nang", mean: 25.8 },
        CityData { name: "Dakar", mean: 24.0 },
        CityData { name: "Dallas", mean: 19.0 },
        CityData { name: "Damascus", mean: 17.0 },
        CityData { name: "Dampier", mean: 26.4 },
        CityData { name: "Dar es Salaam", mean: 25.8 },
        CityData { name: "Darwin", mean: 27.6 },
        CityData { name: "Denpasar", mean: 23.7 },
        CityData { name: "Denver", mean: 10.4 },
        CityData { name: "Detroit", mean: 10.0 },
        CityData { name: "Dhaka", mean: 25.9 },
        CityData { name: "Dikson", mean: -11.1 },
        CityData { name: "Dili", mean: 26.6 },
        CityData { name: "Djibouti", mean: 29.9 },
        CityData { name: "Dodoma", mean: 22.7 },
        CityData { name: "Dolisie", mean: 24.0 },
        CityData { name: "Douala", mean: 26.7 },
        CityData { name: "Dubai", mean: 26.9 },
        CityData { name: "Dublin", mean: 9.8 },
        CityData { name: "Dunedin", mean: 11.1 },
        CityData { name: "Durban", mean: 20.6 },
        CityData { name: "Dushanbe", mean: 14.7 },
        CityData { name: "Edinburgh", mean: 9.3 },
        CityData { name: "Edmonton", mean: 4.2 },
        CityData { name: "El Paso", mean: 18.1 },
        CityData { name: "Entebbe", mean: 21.0 },
        CityData { name: "Erbil", mean: 19.5 },
        CityData { name: "Erzurum", mean: 5.1 },
        CityData { name: "Fairbanks", mean: -2.3 },
        CityData { name: "Fianarantsoa", mean: 17.9 },
        CityData { name: "Flores, Petén", mean: 26.4 },
        CityData { name: "Frankfurt", mean: 10.6 },
        CityData { name: "Fresno", mean: 17.9 },
        CityData { name: "Fukuoka", mean: 17.0 },
        CityData { name: "Gabès", mean: 19.5 },
        CityData { name: "Gaborone", mean: 21.0 },
        CityData { name: "Gagnoa", mean: 26.0 },
        CityData { name: "Gangtok", mean: 15.2 },
        CityData { name: "Garissa", mean: 29.3 },
        CityData { name: "Garoua", mean: 28.3 },
        CityData { name: "George Town", mean: 27.9 },
        CityData { name: "Ghanzi", mean: 21.4 },
        CityData { name: "Gjoa Haven", mean: -14.4 },
        CityData { name: "Guadalajara", mean: 20.9 },
        CityData { name: "Guangzhou", mean: 22.4 },
        CityData { name: "Guatemala City", mean: 20.4 },
        CityData { name: "Halifax", mean: 7.5 },
        CityData { name: "Hamburg", mean: 9.7 },
        CityData { name: "Hamilton", mean: 13.8 },
        CityData { name: "Hanga Roa", mean: 20.5 },
        CityData { name: "Hanoi", mean: 23.6 },
        CityData { name: "Harare", mean: 18.4 },
        CityData { name: "Harbin", mean: 5.0 },
        CityData { name: "Hargeisa", mean: 21.7 },
        CityData { name: "Hat Yai", mean: 27.0 },
        CityData { name: "Havana", mean: 25.2 },
        CityData { name: "Helsinki", mean: 5.9 },
        CityData { name: "Heraklion", mean: 18.9 },
        CityData { name: "Hiroshima", mean: 16.3 },
        CityData { name: "Ho Chi Minh City", mean: 27.4 },
        CityData { name: "Hobart", mean: 12.7 },
        CityData { name: "Hong Kong", mean: 23.3 },
        CityData { name: "Honiara", mean: 26.5 },
        CityData { name: "Honolulu", mean: 25.4 },
        CityData { name: "Houston", mean: 20.8 },
        CityData { name: "Ifrane", mean: 11.4 },
        CityData { name: "Indianapolis", mean: 11.8 },
        CityData { name: "Iqaluit", mean: -9.3 },
        CityData { name: "Irkutsk", mean: 1.0 },
        CityData { name: "Istanbul", mean: 13.9 },
        CityData { name: "İzmir", mean: 17.9 },
        CityData { name: "Jacksonville", mean: 20.3 },
        CityData { name: "Jakarta", mean: 26.7 },
        CityData { name: "Jayapura", mean: 27.0 },
        CityData { name: "Jerusalem", mean: 18.3 },
        CityData { name: "Johannesburg", mean: 15.5 },
        CityData { name: "Jos", mean: 22.8 },
        CityData { name: "Juba", mean: 27.8 },
        CityData { name: "Kabul", mean: 12.1 },
        CityData { name: "Kampala", mean: 20.0 },
        CityData { name: "Kandi", mean: 27.7 },
        CityData { name: "Kankan", mean: 26.5 },
        CityData { name: "Kano", mean: 26.4 },
        CityData { name: "Kansas City", mean: 12.5 },
        CityData { name: "Karachi", mean: 26.0 },
        CityData { name: "Karonga", mean: 24.4 },
        CityData { name: "Kathmandu", mean: 18.3 },
        CityData { name: "Khartoum", mean: 29.9 },
        CityData { name: "Kingston", mean: 27.4 },
        CityData { name: "Kinshasa", mean: 25.3 },
        CityData { name: "Kolkata", mean: 26.7 },
        CityData { name: "Kuala Lumpur", mean: 27.3 },
        CityData { name: "Kumasi", mean: 26.0 },
        CityData { name: "Kunming", mean: 15.7 },
        CityData { name: "Kuopio", mean: 3.4 },
        CityData { name: "Kuwait City", mean: 25.7 },
        CityData { name: "Kyiv", mean: 8.4 },
        CityData { name: "Kyoto", mean: 15.8 },
        CityData { name: "La Ceiba", mean: 26.2 },
        CityData { name: "La Paz", mean: 23.7 },
        CityData { name: "Lagos", mean: 26.8 },
        CityData { name: "Lahore", mean: 24.3 },
        CityData { name: "Lake Havasu City", mean: 23.7 },
        CityData { name: "Lake Tekapo", mean: 8.7 },
        CityData { name: "Las Palmas de Gran Canaria", mean: 21.2 },
        CityData { name: "Las Vegas", mean: 20.3 },
        CityData { name: "Launceston", mean: 13.1 },
        CityData { name: "Lhasa", mean: 7.6 },
        CityData { name: "Libreville", mean: 25.9 },
        CityData { name: "Lisbon", mean: 17.5 },
        CityData { name: "Livingstone", mean: 21.8 },
        CityData { name: "Ljubljana", mean: 10.9 },
        CityData { name: "Lodwar", mean: 29.3 },
        CityData { name: "Lomé", mean: 26.9 },
        CityData { name: "London", mean: 11.3 },
        CityData { name: "Los Angeles", mean: 18.6 },
        CityData { name: "Louisville", mean: 13.9 },
        CityData { name: "Luanda", mean: 25.8 },
        CityData { name: "Lubumbashi", mean: 20.8 },
        CityData { name: "Lusaka", mean: 19.9 },
        CityData { name: "Luxembourg City", mean: 9.3 },
        CityData { name: "Lviv", mean: 7.8 },
        CityData { name: "Lyon", mean: 12.5 },
        CityData { name: "Madrid", mean: 15.0 },
        CityData { name: "Mahajanga", mean: 26.3 },
        CityData { name: "Makassar", mean: 26.7 },
        CityData { name: "Makurdi", mean: 26.0 },
        CityData { name: "Malabo", mean: 26.3 },
        CityData { name: "Malé", mean: 28.0 },
        CityData { name: "Managua", mean: 27.3 },
        CityData { name: "Manama", mean: 26.5 },
        CityData { name: "Mandalay", mean: 28.0 },
        CityData { name: "Mango", mean: 28.1 },
        CityData { name: "Manila", mean: 28.4 },
        CityData { name: "Maputo", mean: 22.8 },
        CityData { name: "Marrakesh", mean: 19.6 },
        CityData { name: "Marseille", mean: 15.8 },
        CityData { name: "Maun", mean: 22.4 },
        CityData { name: "Medan", mean: 26.5 },
        CityData { name: "Mek'ele", mean: 22.7 },
        CityData { name: "Melbourne", mean: 15.1 },
        CityData { name: "Memphis", mean: 17.2 },
        CityData { name: "Mexicali", mean: 23.1 },
        CityData { name: "Mexico City", mean: 17.5 },
        CityData { name: "Miami", mean: 24.9 },
        CityData { name: "Milan", mean: 13.0 },
        CityData { name: "Milwaukee", mean: 8.9 },
        CityData { name: "Minneapolis", mean: 7.8 },
        CityData { name: "Minsk", mean: 6.7 },
        CityData { name: "Mogadishu", mean: 27.1 },
        CityData { name: "Mombasa", mean: 26.3 },
        CityData { name: "Monaco", mean: 16.4 },
        CityData { name: "Moncton", mean: 6.1 },
        CityData { name: "Monterrey", mean: 22.3 },
        CityData { name: "Montreal", mean: 6.8 },
        CityData { name: "Moscow", mean: 5.8 },
        CityData { name: "Mumbai", mean: 27.1 },
        CityData { name: "Murmansk", mean: 0.6 },
        CityData { name: "Muscat", mean: 28.0 },
        CityData { name: "Mzuzu", mean: 17.7 },
        CityData { name: "N'Djamena", mean: 28.3 },
        CityData { name: "Naha", mean: 23.1 },
        CityData { name: "Nairobi", mean: 17.8 },
        CityData { name: "Nakhon Ratchasima", mean: 27.3 },
        CityData { name: "Napier", mean: 14.6 },
        CityData { name: "Napoli", mean: 15.9 },
        CityData { name: "Nashville", mean: 15.4 },
        CityData { name: "Nassau", mean: 24.6 },
        CityData { name: "Ndola", mean: 20.3 },
        CityData { name: "New Delhi", mean: 25.0 },
        CityData { name: "New Orleans", mean: 20.7 },
        CityData { name: "New York City", mean: 12.9 },
        CityData { name: "Ngaoundéré", mean: 22.0 },
        CityData { name: "Niamey", mean: 29.3 },
        CityData { name: "Nicosia", mean: 19.7 },
        CityData { name: "Niigata", mean: 13.9 },
        CityData { name: "Nouadhibou", mean: 21.3 },
        CityData { name: "Nouakchott", mean: 25.7 },
        CityData { name: "Novosibirsk", mean: 1.7 },
        CityData { name: "Nuuk", mean: -1.4 },
        CityData { name: "Odesa", mean: 10.7 },
        CityData { name: "Odienné", mean: 26.0 },
        CityData { name: "Oklahoma City", mean: 15.9 },
        CityData { name: "Omaha", mean: 10.6 },
        CityData { name: "Oranjestad", mean: 28.1 },
        CityData { name: "Oslo", mean: 5.7 },
        CityData { name: "Ottawa", mean: 6.6 },
        CityData { name: "Ouagadougou", mean: 28.3 },
        CityData { name: "Ouahigouya", mean: 28.6 },
        CityData { name: "Ouarzazate", mean: 18.9 },
        CityData { name: "Oulu", mean: 2.7 },
        CityData { name: "Palembang", mean: 27.3 },
        CityData { name: "Palermo", mean: 18.5 },
        CityData { name: "Palm Springs", mean: 24.5 },
        CityData { name: "Palmerston North", mean: 13.2 },
        CityData { name: "Panama City", mean: 28.0 },
        CityData { name: "Parakou", mean: 26.8 },
        CityData { name: "Paris", mean: 12.3 },
        CityData { name: "Perth", mean: 18.7 },
        CityData { name: "Petropavlovsk-Kamchatsky", mean: 1.9 },
        CityData { name: "Philadelphia", mean: 13.2 },
        CityData { name: "Phnom Penh", mean: 28.3 },
        CityData { name: "Phoenix", mean: 23.9 },
        CityData { name: "Pittsburgh", mean: 10.8 },
        CityData { name: "Podgorica", mean: 15.3 },
        CityData { name: "Pointe-Noire", mean: 26.1 },
        CityData { name: "Pontianak", mean: 27.7 },
        CityData { name: "Port Moresby", mean: 26.9 },
        CityData { name: "Port Sudan", mean: 28.4 },
        CityData { name: "Port Vila", mean: 24.3 },
        CityData { name: "Port-Gentil", mean: 26.0 },
        CityData { name: "Portland {OR}", mean: 12.4 },
        CityData { name: "Porto", mean: 15.7 },
        CityData { name: "Prague", mean: 8.4 },
        CityData { name: "Praia", mean: 24.4 },
        CityData { name: "Pretoria", mean: 18.2 },
        CityData { name: "Pyongyang", mean: 10.8 },
        CityData { name: "Rabat", mean: 17.2 },
        CityData { name: "Rangpur", mean: 24.4 },
        CityData { name: "Reggane", mean: 28.3 },
        CityData { name: "Reykjavík", mean: 4.3 },
        CityData { name: "Riga", mean: 6.2 },
        CityData { name: "Riyadh", mean: 26.0 },
        CityData { name: "Rome", mean: 15.2 },
        CityData { name: "Roseau", mean: 26.2 },
        CityData { name: "Rostov-on-Don", mean: 9.9 },
        CityData { name: "Sacramento", mean: 16.3 },
        CityData { name: "Saint Petersburg", mean: 5.8 },
        CityData { name: "Saint-Pierre", mean: 5.7 },
        CityData { name: "Salt Lake City", mean: 11.6 },
        CityData { name: "San Antonio", mean: 20.8 },
        CityData { name: "San Diego", mean: 17.8 },
        CityData { name: "San Francisco", mean: 14.6 },
        CityData { name: "San Jose", mean: 16.4 },
        CityData { name: "San José", mean: 22.6 },
        CityData { name: "San Juan", mean: 27.2 },
        CityData { name: "San Salvador", mean: 23.1 },
        CityData { name: "Sana'a", mean: 20.0 },
        CityData { name: "Santo Domingo", mean: 25.9 },
        CityData { name: "Sapporo", mean: 8.9 },
        CityData { name: "Sarajevo", mean: 10.1 },
        CityData { name: "Saskatoon", mean: 3.3 },
        CityData { name: "Seattle", mean: 11.3 },
        CityData { name: "Ségou", mean: 28.0 },
        CityData { name: "Seoul", mean: 12.5 },
        CityData { name: "Seville", mean: 19.2 },
        CityData { name: "Shanghai", mean: 16.7 },
        CityData { name: "Singapore", mean: 27.0 },
        CityData { name: "Skopje", mean: 12.4 },
        CityData { name: "Sochi", mean: 14.2 },
        CityData { name: "Sofia", mean: 10.6 },
        CityData { name: "Sokoto", mean: 28.0 },
        CityData { name: "Split", mean: 16.1 },
        CityData { name: "St. John's", mean: 5.0 },
        CityData { name: "St. Louis", mean: 13.9 },
        CityData { name: "Stockholm", mean: 6.6 },
        CityData { name: "Surabaya", mean: 27.1 },
        CityData { name: "Suva", mean: 25.6 },
        CityData { name: "Suwałki", mean: 7.2 },
        CityData { name: "Sydney", mean: 17.7 },
        CityData { name: "Tabora", mean: 23.0 },
        CityData { name: "Tabriz", mean: 12.6 },
        CityData { name: "Taipei", mean: 23.0 },
        CityData { name: "Tallinn", mean: 6.4 },
        CityData { name: "Tamale", mean: 27.9 },
        CityData { name: "Tamanrasset", mean: 21.7 },
        CityData { name: "Tampa", mean: 22.9 },
        CityData { name: "Tashkent", mean: 14.8 },
        CityData { name: "Tauranga", mean: 14.8 },
        CityData { name: "Tbilisi", mean: 12.9 },
        CityData { name: "Tegucigalpa", mean: 21.7 },
        CityData { name: "Tehran", mean: 17.0 },
        CityData { name: "Tel Aviv", mean: 20.0 },
        CityData { name: "Thessaloniki", mean: 16.0 },
        CityData { name: "Thiès", mean: 24.0 },
        CityData { name: "Tijuana", mean: 17.8 },
        CityData { name: "Timbuktu", mean: 28.0 },
        CityData { name: "Tirana", mean: 15.2 },
        CityData { name: "Toamasina", mean: 23.4 },
        CityData { name: "Tokyo", mean: 15.4 },
        CityData { name: "Toliara", mean: 24.1 },
        CityData { name: "Toluca", mean: 12.4 },
        CityData { name: "Toronto", mean: 9.4 },
        CityData { name: "Tripoli", mean: 20.0 },
        CityData { name: "Tromsø", mean: 2.9 },
        CityData { name: "Tucson", mean: 20.9 },
        CityData { name: "Tunis", mean: 18.4 },
        CityData { name: "Ulaanbaatar", mean: -0.4 },
        CityData { name: "Upington", mean: 20.4 },
        CityData { name: "Ürümqi", mean: 7.4 },
        CityData { name: "Vaduz", mean: 10.1 },
        CityData { name: "Valencia", mean: 18.3 },
        CityData { name: "Valletta", mean: 18.8 },
        CityData { name: "Vancouver", mean: 10.4 },
        CityData { name: "Veracruz", mean: 25.4 },
        CityData { name: "Vienna", mean: 10.4 },
        CityData { name: "Vientiane", mean: 25.9 },
        CityData { name: "Villahermosa", mean: 27.1 },
        CityData { name: "Vilnius", mean: 6.0 },
        CityData { name: "Virginia Beach", mean: 15.8 },
        CityData { name: "Vladivostok", mean: 4.9 },
        CityData { name: "Warsaw", mean: 8.5 },
        CityData { name: "Washington, mean: D.C.", mean: 14.6 },
        CityData { name: "Wau", mean: 27.8 },
        CityData { name: "Wellington", mean: 12.9 },
        CityData { name: "Whitehorse", mean: -0.1 },
        CityData { name: "Wichita", mean: 13.9 },
        CityData { name: "Willemstad", mean: 28.0 },
        CityData { name: "Winnipeg", mean: 3.0 },
        CityData { name: "Wrocław", mean: 9.6 },
        CityData { name: "Xi'an", mean: 14.1 },
        CityData { name: "Yakutsk", mean: -8.8 },
        CityData { name: "Yangon", mean: 27.5 },
        CityData { name: "Yaoundé", mean: 23.8 },
        CityData { name: "Yellowknife", mean: -4.3 },
        CityData { name: "Yerevan", mean: 12.4 },
        CityData { name: "Yinchuan", mean: 9.0 },
        CityData { name: "Zagreb", mean: 10.7 },
        CityData { name: "Zanzibar City", mean: 26.0 },
        CityData { name: "Zürich", mean: 9.3 },
	];
	
	let args: Vec<String> = env::args().collect();

	if args.len() < 2 {
		panic!("usage: {} Number-of-samples [filename]", args[0]);
	}
    let number_of_samples: usize = args[1].parse().expect("Expected a number");
    let stddev                   = 2.0;  
    let seed: u64                = 15112024;
    let city_number_distribution = Uniform::from(0..cities.len());
        
    let mut rng = StdRng::seed_from_u64(seed);

	let mut stream : Box<dyn Write> = if args.len() == 2 {
		Box::new(stdout())		
	} else {
		let name = &args[2];
		let file = File::create(name).unwrap_or_else(|err| panic!("Can't open {name}: {err}"));
		Box::new(file)
    };
       
    let mut output = BufWriter::with_capacity(10_000_000, &mut stream);

	for count in 0..number_of_samples {
		let city_number = city_number_distribution.sample(&mut rng);
		debug_assert!((0..cities.len()).contains(&city_number));
		let temperature_distribution = Normal::new(cities[city_number].mean, stddev).expect("Failed to create distribution");
		let temperature = temperature_distribution.sample(&mut rng);

		writeln!(output, "{};{:.1}", cities[city_number].name, temperature).unwrap();
		
		if count % 10_000_000 == 0 {
			eprint!(".");
			stderr().flush().unwrap();
		}
	}		  
}

